# Model arguments
model_revision: main
torch_dtype: float16
attn_implementation: flash_attention_2
bf16: true
tf32: true

# Dataset arguments
dataset_id_or_path: "openai/gsm8k"

# Training arguments
max_steps: 1 # Original 450
num_train_epochs: 1
gradient_accumulation_steps: 16 # Ditingkatkan untuk kompensasi batch size kecil
gradient_checkpointing: true
gradient_checkpointing_kwargs:
    use_reentrant: false
learning_rate: 2.0e-6 # Sedikit lebih tinggi untuk optimisasi yang lebih baik
lr_scheduler_type: cosine
warmup_ratio: 0.1 # Increase from 0.05 for better initialization

# GRPO arguments
use_vllm: true
####################################################################
vllm_args:
    enforce_eager: true # Add this to run in eager mode
    gpu_memory_utilization: 0.65 # Diturunkan untuk mencegah OOM
    max_num_seqs: 32 # Dikurangi sesuai kapasitas GPU
####################################################################
num_generations: 4 # Increase from 2
per_device_train_batch_size: 1 # Dikurangi karena memori terbatas
beta: 0.01 # Naikkan nilai beta
max_prompt_length: 256 # Increase if memory allows
max_completion_length: 256 # Reduced from 512

# Logging arguments
logging_strategy: steps
logging_steps: 2
report_to:
    - tensorboard
save_strategy: "steps"
save_steps: 10
seed: 42

# Script arguments
public_maddr: "/ip4/38.101.215.14/tcp/31222"
host_maddr: "/ip4/0.0.0.0/tcp/38331"
max_rounds: 10000

# Model-specific arguments
model_name_or_path: Gensyn/Qwen2.5-0.5B-Instruct
output_dir: runs/gsm8k/multinode/Qwen2.5-0.5B-Instruct-Gensyn-Swarm
